//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchStore25.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUCT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PRODUCT()
        {
            this.DETAIL_ORDER = new HashSet<DETAIL_ORDER>();
            this.RATE_PRODUCT = new HashSet<RATE_PRODUCT>();
        }
    
        public int idProduct { get; set; }
        public string name { get; set; }
        public Nullable<bool> idTypeProduct { get; set; }
        public string detail { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<int> inventory { get; set; }
        public Nullable<decimal> amount { get; set; }
        public string img { get; set; }
        public Nullable<int> tax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETAIL_ORDER> DETAIL_ORDER { get; set; }
        public virtual TYPE_PRODUCT TYPE_PRODUCT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RATE_PRODUCT> RATE_PRODUCT { get; set; }
    }
}
